CREATE TABLE IF NOT EXISTS schema_migration (version text PRIMARY KEY, sha256 char(64) NOT NULL, applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_account (
  id uuid PRIMARY KEY, username varchar(120) NOT NULL UNIQUE, staff_identifier varchar(120), display_name varchar(240) NOT NULL,
  job_title varchar(240), account_type varchar(16) NOT NULL CHECK (account_type IN ('ADMIN','OPERATIONAL')),
  password_hash text NOT NULL, must_change_password boolean NOT NULL DEFAULT true, is_active boolean NOT NULL DEFAULT true,
  failed_login_count integer NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0), locked_until timestamptz,
  password_changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE auth_session (
  id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES user_account(id), token_hash char(64) NOT NULL UNIQUE, csrf_secret_hash char(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, last_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  idle_expires_at timestamptz NOT NULL, absolute_expires_at timestamptz NOT NULL, revoked_at timestamptz, revoked_reason varchar(80),
  rotated_from_session_id uuid REFERENCES auth_session(id), created_ip varchar(64), user_agent varchar(1000)
);
CREATE TABLE auth_login_attempt (id uuid PRIMARY KEY, identifier_fingerprint char(64) NOT NULL, ip_address varchar(64), was_successful boolean NOT NULL, failure_reason varchar(80), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE routing_unit (id uuid PRIMARY KEY, code varchar(80) NOT NULL UNIQUE, name_ar varchar(240) NOT NULL UNIQUE, name_en varchar(240), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE operational_unit (
  id uuid PRIMARY KEY, kind varchar(8) NOT NULL CHECK (kind IN ('HR','ORG','AUTH')), name varchar(240) NOT NULL,
  routing_unit_id uuid REFERENCES routing_unit(id), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT operational_unit_routing_shape CHECK ((kind = 'AUTH' AND routing_unit_id IS NOT NULL) OR (kind IN ('HR','ORG') AND routing_unit_id IS NULL))
);
CREATE UNIQUE INDEX operational_unit_one_active_hr ON operational_unit(kind) WHERE kind='HR' AND is_active;
CREATE UNIQUE INDEX operational_unit_one_active_org ON operational_unit(kind) WHERE kind='ORG' AND is_active;
CREATE UNIQUE INDEX operational_unit_one_active_auth_per_routing ON operational_unit(routing_unit_id) WHERE kind='AUTH' AND is_active;
CREATE TABLE user_unit_membership (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES user_account(id), unit_id uuid NOT NULL REFERENCES operational_unit(id), effective_from timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, effective_to timestamptz, created_by_user_id uuid NOT NULL REFERENCES user_account(id), ended_by_user_id uuid REFERENCES user_account(id), end_reason varchar(500), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (effective_to IS NULL OR effective_to > effective_from));
CREATE UNIQUE INDEX user_unit_membership_one_active_per_user ON user_unit_membership(user_id) WHERE effective_to IS NULL;
CREATE TABLE unit_manager_assignment (id uuid PRIMARY KEY, unit_id uuid NOT NULL REFERENCES operational_unit(id), manager_user_id uuid NOT NULL REFERENCES user_account(id), effective_from timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, effective_to timestamptz, assigned_by_user_id uuid NOT NULL REFERENCES user_account(id), ended_by_user_id uuid REFERENCES user_account(id), replacement_reason varchar(500), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (effective_to IS NULL OR effective_to > effective_from));
CREATE UNIQUE INDEX unit_manager_assignment_one_active_per_unit ON unit_manager_assignment(unit_id) WHERE effective_to IS NULL;
CREATE TABLE audit_event (id uuid PRIMARY KEY, actor_user_id uuid REFERENCES user_account(id), event_type varchar(100) NOT NULL, subject_type varchar(80), subject_id uuid, details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE security_event (id uuid PRIMARY KEY, actor_user_id uuid REFERENCES user_account(id), event_type varchar(100) NOT NULL, ip_address varchar(64), user_agent varchar(1000), details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_signature_asset (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES user_account(id), storage_key text NOT NULL UNIQUE, mime_type varchar(100) NOT NULL, byte_size integer NOT NULL, sha256 char(64) NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE import_batch (id uuid PRIMARY KEY, snapshot_year integer NOT NULL, source_filename varchar(500) NOT NULL, source_sha256 char(64) NOT NULL, detected_headers jsonb NOT NULL DEFAULT '[]'::jsonb, status varchar(20) NOT NULL, row_count integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, activated_at timestamptz);
CREATE TABLE employee_import_staging_row (id uuid PRIMARY KEY, import_batch_id uuid NOT NULL REFERENCES import_batch(id), source_row_number integer NOT NULL, raw_data jsonb NOT NULL, normalized_data jsonb NOT NULL DEFAULT '{}'::jsonb, routing_unit_id uuid REFERENCES routing_unit(id), validation_status varchar(20) NOT NULL DEFAULT 'PENDING', validation_messages jsonb NOT NULL DEFAULT '[]'::jsonb);
CREATE TABLE employee (id uuid PRIMARY KEY, personnel_number varchar(120) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE employee_annual_snapshot (id uuid PRIMARY KEY, employee_id uuid NOT NULL REFERENCES employee(id), import_batch_id uuid NOT NULL REFERENCES import_batch(id), snapshot_year integer NOT NULL, personnel_number varchar(120) NOT NULL, routing_unit_id uuid REFERENCES routing_unit(id), employee_data jsonb NOT NULL, UNIQUE(snapshot_year, personnel_number));
CREATE TABLE routing_unit_source_alias (id uuid PRIMARY KEY, source_label varchar(500) NOT NULL UNIQUE, routing_unit_id uuid NOT NULL REFERENCES routing_unit(id), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE job_category_reference (id uuid PRIMARY KEY, code varchar(80) NOT NULL UNIQUE, name varchar(240) NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE qualification_status_reference (id uuid PRIMARY KEY, code varchar(80) NOT NULL UNIQUE, name varchar(240) NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE workflow_request (id uuid PRIMARY KEY, request_number varchar(80) NOT NULL UNIQUE, request_type varchar(20) NOT NULL, routing_unit_id uuid REFERENCES routing_unit(id), status varchar(60) NOT NULL, current_iteration_id uuid, current_stage_code varchar(10), version integer NOT NULL DEFAULT 1, created_by_user_id uuid REFERENCES user_account(id), created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at timestamptz, cancelled_at timestamptz);
CREATE TABLE workflow_iteration (id uuid PRIMARY KEY, request_id uuid NOT NULL REFERENCES workflow_request(id), iteration_no integer NOT NULL, status varchar(60) NOT NULL, parent_iteration_id uuid REFERENCES workflow_iteration(id), started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, ended_at timestamptz, rejection_reason text, UNIQUE(request_id, iteration_no));
ALTER TABLE workflow_request ADD CONSTRAINT workflow_request_current_iteration_fk FOREIGN KEY (current_iteration_id) REFERENCES workflow_iteration(id);
CREATE TABLE request_form_section (id uuid PRIMARY KEY, request_id uuid NOT NULL REFERENCES workflow_request(id), category varchar(80) NOT NULL, display_order integer NOT NULL, data jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE(request_id, category));
CREATE TABLE request_candidate (id uuid PRIMARY KEY, request_id uuid NOT NULL REFERENCES workflow_request(id), employee_snapshot_id uuid NOT NULL REFERENCES employee_annual_snapshot(id), frozen_data jsonb NOT NULL, accepted_data jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE(request_id, employee_snapshot_id));
CREATE TABLE stage_execution (id uuid PRIMARY KEY, iteration_id uuid NOT NULL REFERENCES workflow_iteration(id), stage_code varchar(10) NOT NULL, execution_no integer NOT NULL, responsible_unit_id uuid NOT NULL REFERENCES operational_unit(id), status varchar(40) NOT NULL, work_state varchar(40) NOT NULL, opened_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at timestamptz, previous_execution_id uuid REFERENCES stage_execution(id), UNIQUE(iteration_id, stage_code, execution_no));
CREATE TABLE work_assignment (id uuid PRIMARY KEY, stage_execution_id uuid NOT NULL REFERENCES stage_execution(id), assigned_by_user_id uuid NOT NULL REFERENCES user_account(id), assigned_to_user_id uuid NOT NULL REFERENCES user_account(id), assigned_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, ended_at timestamptz, end_reason varchar(500));
CREATE UNIQUE INDEX work_assignment_one_active_per_execution ON work_assignment(stage_execution_id) WHERE ended_at IS NULL;
CREATE TABLE stage_submission_snapshot (id uuid PRIMARY KEY, stage_execution_id uuid NOT NULL UNIQUE REFERENCES stage_execution(id), payload jsonb NOT NULL, sha256 char(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE workflow_note (id uuid PRIMARY KEY, request_id uuid NOT NULL REFERENCES workflow_request(id), candidate_id uuid REFERENCES request_candidate(id), iteration_id uuid REFERENCES workflow_iteration(id), stage_execution_id uuid REFERENCES stage_execution(id), author_user_id uuid NOT NULL REFERENCES user_account(id), unit_id uuid REFERENCES operational_unit(id), body text NOT NULL, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE stage_action (id uuid PRIMARY KEY, stage_execution_id uuid NOT NULL REFERENCES stage_execution(id), actor_user_id uuid NOT NULL REFERENCES user_account(id), unit_id uuid REFERENCES operational_unit(id), action_type varchar(100) NOT NULL, reason text, payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE promotion_decision (id uuid PRIMARY KEY, stage_execution_id uuid NOT NULL REFERENCES stage_execution(id), candidate_id uuid NOT NULL REFERENCES request_candidate(id), decision_type varchar(20) NOT NULL CHECK (decision_type IN ('SAME_POSITION','OTHER_POSITION')), target_job_title varchar(240), recommendation varchar(80), notes text, UNIQUE(stage_execution_id,candidate_id), CHECK ((decision_type='OTHER_POSITION' AND target_job_title IS NOT NULL) OR decision_type='SAME_POSITION'));
CREATE TABLE secondment_position_option (id uuid PRIMARY KEY, candidate_id uuid NOT NULL REFERENCES request_candidate(id), source_stage_execution_id uuid NOT NULL REFERENCES stage_execution(id), position_title varchar(240) NOT NULL, organizational_dependency varchar(240), qualification_status varchar(80), display_order integer NOT NULL);
CREATE TABLE secondment_decision (id uuid PRIMARY KEY, stage_execution_id uuid NOT NULL REFERENCES stage_execution(id), candidate_id uuid NOT NULL REFERENCES request_candidate(id), selected_option_id uuid NOT NULL REFERENCES secondment_position_option(id), UNIQUE(stage_execution_id,candidate_id));
CREATE TABLE workflow_signoff (id uuid PRIMARY KEY, stage_execution_id uuid NOT NULL UNIQUE REFERENCES stage_execution(id), signer_user_id uuid NOT NULL REFERENCES user_account(id), manager_assignment_id uuid REFERENCES unit_manager_assignment(id), signer_snapshot jsonb NOT NULL, signature_asset_id uuid REFERENCES user_signature_asset(id), signature_sha256 char(64), signed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE final_form_snapshot (id uuid PRIMARY KEY, request_id uuid NOT NULL REFERENCES workflow_request(id), iteration_id uuid NOT NULL REFERENCES workflow_iteration(id), template_version varchar(80) NOT NULL, payload jsonb NOT NULL, sha256 char(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(iteration_id));
CREATE TABLE frozen_pdf_document (id uuid PRIMARY KEY, final_form_snapshot_id uuid NOT NULL REFERENCES final_form_snapshot(id), storage_key text NOT NULL UNIQUE, sha256 char(64) NOT NULL, byte_size integer NOT NULL, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE pdf_generation_log (id uuid PRIMARY KEY, request_id uuid REFERENCES workflow_request(id), document_kind varchar(80) NOT NULL, succeeded boolean NOT NULL, safe_metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notification (id uuid PRIMARY KEY, recipient_user_id uuid NOT NULL REFERENCES user_account(id), request_id uuid REFERENCES workflow_request(id), stage_execution_id uuid REFERENCES stage_execution(id), notification_type varchar(80) NOT NULL, is_read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
