import { randomUUID } from 'node:crypto'
import type { Pool } from 'pg'
import type { AppConfig } from '../../config/env.ts'
import { withTransaction } from '../../db/transaction.ts'
import type { RequestEvidence } from '../../middleware/request-context.ts'
import { AppError, isUniqueViolation } from '../../shared/errors.ts'
import { bool, optionalText, password, text, uuid } from '../../shared/validation.ts'
import { LocalAuthenticationProvider } from '../auth/local-authentication-provider.ts'

type Actor={userId:string}
const audit=async(db:any,actor:Actor,type:string,subjectType:string,subjectId:string,details:unknown,e:RequestEvidence)=>{ await db.query(`INSERT INTO audit_event(id,actor_user_id,event_type,subject_type,subject_id,details) VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),actor.userId,type,subjectType,subjectId,JSON.stringify(details)]); await db.query(`INSERT INTO security_event(id,actor_user_id,event_type,ip_address,user_agent,details) VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),actor.userId,type,e.ipAddress,e.userAgent??null,'{}']) }

export class V5AdminService {
  private auth:LocalAuthenticationProvider
  constructor(private readonly pool:Pool,config:AppConfig){this.auth=new LocalAuthenticationProvider(pool,config)}
  async listAccounts(){return (await this.pool.query(`SELECT id,username,staff_identifier AS "staffIdentifier",display_name AS "displayName",job_title AS "jobTitle",account_type AS "accountType",must_change_password AS "mustChangePassword",is_active AS "isActive",locked_until AS "lockedUntil",version,created_at AS "createdAt" FROM user_account ORDER BY username`)).rows}
  async account(id:string){const r=await this.pool.query(`SELECT id,username,staff_identifier AS "staffIdentifier",display_name AS "displayName",job_title AS "jobTitle",account_type AS "accountType",must_change_password AS "mustChangePassword",is_active AS "isActive",locked_until AS "lockedUntil",version FROM user_account WHERE id=$1`,[uuid(id,'account id')]);if(!r.rows[0])throw new AppError(404,'Account not found');return r.rows[0]}
  async createAccount(actor:Actor,body:Record<string,unknown>,e:RequestEvidence){const accountType=body.accountType==='ADMIN'||body.accountType==='OPERATIONAL'?body.accountType:null;if(!accountType)throw new AppError(400,'accountType must be ADMIN or OPERATIONAL');const id=randomUUID(), unitId=body.unitId===undefined?null:uuid(body.unitId,'unitId');if(accountType==='ADMIN'&&unitId)throw new AppError(400,'ADMIN cannot have operational membership');if(accountType==='OPERATIONAL'&&!unitId)throw new AppError(400,'OPERATIONAL requires initial unitId');const hash=await this.auth.hashPassword(password(body.temporaryPassword,'temporaryPassword'));try{return await withTransaction(this.pool,async db=>{const forbiddenKeys=['isManager','role','activeRole'];for(const k of forbiddenKeys){if(body[k]!==undefined)throw new AppError(400,`Field ${k} is forbidden`)}await db.query(`INSERT INTO user_account(id,username,staff_identifier,display_name,job_title,account_type,password_hash,must_change_password,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,TRUE,$8)`,[id,text(body.username,'username',120,3),optionalText(body.staffIdentifier,'staffIdentifier',120),text(body.displayName,'displayName',240),optionalText(body.jobTitle,'jobTitle',240),accountType,hash,body.isActive===undefined?true:bool(body.isActive,'isActive')]);if(unitId)await db.query(`INSERT INTO user_unit_membership(id,user_id,unit_id,created_by_user_id) VALUES($1,$2,$3,$4)`,[randomUUID(),id,unitId,actor.userId]);await audit(db,actor,'ACCOUNT_CREATED','user_account',id,{accountType,unitId},e);return await this.account(id)})}catch(error){if(isUniqueViolation(error))throw new AppError(409,'Username or active membership already exists','CONFLICT');throw error}}
  async updateAccount(actor:Actor,id:string,body:Record<string,unknown>,e:RequestEvidence){await this.account(id);return await withTransaction(this.pool,async db=>{await db.query(`UPDATE user_account SET staff_identifier=$2,display_name=$3,job_title=$4,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=$1`,[id,optionalText(body.staffIdentifier,'staffIdentifier',120),text(body.displayName,'displayName',240),optionalText(body.jobTitle,'jobTitle',240)]);await audit(db,actor,'ACCOUNT_UPDATED','user_account',id,{},e);return await this.account(id)})}
  async setAccountActive(actor:Actor,id:string,active:boolean,e:RequestEvidence){return await withTransaction(this.pool,async db=>{const updated=await db.query(`UPDATE user_account SET is_active=$2,version=version+1 WHERE id=$1`,[id,active]);if(!updated.rowCount)throw new AppError(404,'Account not found');if(!active)await db.query(`UPDATE auth_session SET revoked_at=CURRENT_TIMESTAMP,revoked_reason='ACCOUNT_DISABLED' WHERE user_id=$1 AND revoked_at IS NULL`,[id]);await audit(db,actor,active?'ACCOUNT_ENABLED':'ACCOUNT_DISABLED','user_account',id,{},e);return await this.account(id)})}
  async unlock(actor:Actor,id:string,e:RequestEvidence){await this.pool.query(`UPDATE user_account SET locked_until=NULL,failed_login_count=0,version=version+1 WHERE id=$1`,[id]);await this.pool.query(`INSERT INTO audit_event(id,actor_user_id,event_type,subject_type,subject_id,details) VALUES($1,$2,'ACCOUNT_UNLOCKED','user_account',$3,'{}')`,[randomUUID(),actor.userId,id]);return await this.account(id)}
  async resetPassword(actor:Actor,id:string,value:unknown,e:RequestEvidence){const hash=await this.auth.hashPassword(password(value,'temporaryPassword'));await withTransaction(this.pool,async db=>{await db.query(`UPDATE user_account SET password_hash=$2,must_change_password=TRUE,password_changed_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=$1`,[id,hash]);await db.query(`UPDATE auth_session SET revoked_at=CURRENT_TIMESTAMP,revoked_reason='PASSWORD_RESET' WHERE user_id=$1 AND revoked_at IS NULL`,[id]);await audit(db,actor,'PASSWORD_RESET','user_account',id,{},e)});return await this.account(id)}
  async units(){return (await this.pool.query(`SELECT u.id,u.kind,u.name,u.routing_unit_id AS "routingUnitId",u.is_active AS "isActive",r.code AS "routingUnitCode",r.name_ar AS "routingUnitName" FROM operational_unit u LEFT JOIN routing_unit r ON r.id=u.routing_unit_id ORDER BY u.kind,u.name`)).rows}
  async createUnit(actor:Actor,body:Record<string,unknown>,e:RequestEvidence){const kind=body.kind;if(kind!=='HR'&&kind!=='ORG'&&kind!=='AUTH')throw new AppError(400,'kind must be HR, ORG, or AUTH');const routing=body.routingUnitId===undefined?null:uuid(body.routingUnitId,'routingUnitId');if((kind==='AUTH')!==Boolean(routing))throw new AppError(400,'AUTH requires routingUnitId; HR/ORG must not have one');const id=randomUUID();try{await this.pool.query(`INSERT INTO operational_unit(id,kind,name,routing_unit_id,is_active) VALUES($1,$2,$3,$4,TRUE)`,[id,kind,text(body.name,'name',240),routing]);await this.pool.query(`INSERT INTO audit_event(id,actor_user_id,event_type,subject_type,subject_id,details) VALUES($1,$2,'OPERATIONAL_UNIT_CREATED','operational_unit',$3,'{}')`,[randomUUID(),actor.userId,id]);return (await this.pool.query(`SELECT id,kind,name,routing_unit_id AS "routingUnitId",is_active AS "isActive" FROM operational_unit WHERE id=$1`,[id])).rows[0]}catch(error){if(isUniqueViolation(error)){const msg=kind==='AUTH'?'Active routing unit conflict':'Active unit constraint conflict';throw new AppError(409,msg,'CONFLICT')}throw error}}
  async members(unitId:string){return (await this.pool.query(`SELECT m.id AS "membershipId",a.id,a.username,a.display_name AS "displayName",a.job_title AS "jobTitle",m.effective_from AS "effectiveFrom",ma.id AS "managerAssignmentId" FROM user_unit_membership m JOIN user_account a ON a.id=m.user_id LEFT JOIN unit_manager_assignment ma ON ma.unit_id=m.unit_id AND ma.manager_user_id=m.user_id AND ma.effective_to IS NULL WHERE m.unit_id=$1 AND m.effective_to IS NULL ORDER BY a.display_name`,[unitId])).rows}
  async transfer(actor:Actor,unitId:string,body:Record<string,unknown>,e:RequestEvidence){const userId=uuid(body.userId,'userId');try{return await withTransaction(this.pool,async db=>{await db.query(`SELECT id FROM operational_unit WHERE id=$1 FOR UPDATE`,[unitId]);const user=(await db.query(`SELECT account_type,is_active FROM user_account WHERE id=$1 FOR UPDATE`,[userId])).rows[0];if(!user||user.account_type!=='OPERATIONAL'||!user.is_active)throw new AppError(400,'Membership target must be an active OPERATIONAL account');const manager=(await db.query(`SELECT 1 FROM unit_manager_assignment WHERE manager_user_id=$1 AND effective_to IS NULL`,[userId])).rows[0];if(manager)throw new AppError(409,'Replace manager before transferring membership','MANAGER_REPLACEMENT_REQUIRED');await db.query(`UPDATE user_unit_membership SET effective_to=CURRENT_TIMESTAMP,ended_by_user_id=$2,end_reason='TRANSFER' WHERE user_id=$1 AND effective_to IS NULL`,[userId,actor.userId]);const id=randomUUID();await db.query(`INSERT INTO user_unit_membership(id,user_id,unit_id,created_by_user_id) VALUES($1,$2,$3,$4)`,[id,userId,unitId,actor.userId]);await audit(db,actor,'MEMBERSHIP_TRANSFERRED','user_unit_membership',id,{userId,unitId},e);return {membershipId:id}})}catch(error){if(isUniqueViolation(error))throw new AppError(409,'Only one active membership is allowed','CONFLICT');throw error}}
  async replaceManager(actor:Actor,unitId:string,body:Record<string,unknown>,e:RequestEvidence){const managerId=uuid(body.managerUserId,'managerUserId'),reason=optionalText(body.replacementReason,'replacementReason',500);try{return await withTransaction(this.pool,async db=>{ const admin=(await db.query(`SELECT account_type FROM user_account WHERE id=$1`,[actor.userId])).rows[0]; if(!admin||admin.account_type!=='ADMIN')throw new AppError(403,'Admin authority required'); const unit=(await db.query(`SELECT id,is_active FROM operational_unit WHERE id=$1 FOR UPDATE`,[unitId])).rows[0];if(!unit||!unit.is_active)throw new AppError(404,'Active operational unit not found');const target=(await db.query(`SELECT a.id FROM user_account a JOIN user_unit_membership m ON m.user_id=a.id AND m.unit_id=$2 AND m.effective_to IS NULL WHERE a.id=$1 AND a.account_type='OPERATIONAL' AND a.is_active FOR UPDATE`,[managerId,unitId])).rows[0];if(!target)throw new AppError(400,'Manager must be an active OPERATIONAL member of this unit');await db.query(`SELECT id FROM unit_manager_assignment WHERE unit_id=$1 AND effective_to IS NULL FOR UPDATE`,[unitId]);await db.query(`UPDATE unit_manager_assignment SET effective_to=CURRENT_TIMESTAMP,ended_by_user_id=$2,replacement_reason=$3 WHERE unit_id=$1 AND effective_to IS NULL`,[unitId,actor.userId,reason]);const id=randomUUID();await db.query(`INSERT INTO unit_manager_assignment(id,unit_id,manager_user_id,assigned_by_user_id) VALUES($1,$2,$3,$4)`,[id,unitId,managerId,actor.userId]);await audit(db,actor,'MANAGER_REPLACED','unit_manager_assignment',id,{unitId,managerId},e);return {managerAssignmentId:id}})}catch(error){if(isUniqueViolation(error))throw new AppError(409,'Concurrent manager replacement conflict; retry','MANAGER_ASSIGNMENT_CONFLICT');throw error}}
}
